# Generated by Django 4.1 on 2022-12-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("Sector", models.CharField(max_length=50)),
                ("Company", models.CharField(max_length=50)),
                (
                    "Symbol",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("EOD_Price", models.FloatField()),
                ("Expected_Price", models.FloatField()),
            ],
        ),
    ]
