# Generated by Django 4.1 on 2023-01-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Broker", "0005_option_trade_option_profit_loss_option_portfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option", name="Opt_Type", field=models.CharField(max_length=2),
        ),
    ]
