# Generated by Django 4.1 on 2023-01-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Broker", "0006_alter_option_opt_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="Opt_Type",
            field=models.CharField(choices=[("CE", "CE"), ("PE", "PE")], max_length=2),
        ),
    ]
