# Generated by Django 4.1 on 2023-01-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Broker", "0007_alter_option_opt_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Valuation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Shares_Outstanding", models.IntegerField()),
                ("Beta", models.FloatField()),
                ("Cost_Of_Equity", models.FloatField()),
                ("Cost_Of_Debt", models.FloatField()),
                ("Debt_to_Equity", models.FloatField()),
                ("Cost_Of_Capital", models.FloatField()),
                ("Value1", models.FloatField()),
                ("Value2", models.FloatField()),
                ("Value3", models.FloatField()),
                ("Value4", models.FloatField()),
                ("Value5", models.FloatField()),
                ("EV_Sales", models.FloatField()),
                ("EV_Ebit", models.FloatField()),
                ("PE_Ratio", models.FloatField()),
                ("PB_Ratio", models.FloatField()),
                ("Expected_YR_Returns", models.FloatField()),
                (
                    "Stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Broker.stock"
                    ),
                ),
            ],
        ),
    ]
